# Generated by Django 5.0.1 on 2024-02-18 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_manual_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='hero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dota_manual_app.hero'),
            preserve_default=False,
        ),
    ]
