# Generated by Django 5.0.1 on 2024-02-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dota_manual_app', '0002_build_hero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='hero',
            new_name='hero_name',
        ),
    ]
